# Generated by Django 4.2 on 2023-06-17 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='FirstName',
            new_name='Firstname',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='LastName',
            new_name='Lastname',
        ),
    ]
